name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
      - test_release_0.0.1
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/AG-ASCII/ASCII-RFSX/_git/az-rfsim-gr-public-mods
            azure-pipeline-name: 'az-rfsim-gr-public-mods'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
