name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  push:
    branches:
      - main
      - test_release_0.0.1
  pull_request:
    branches: 
      - main

jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "This step runs in the default shell"
      - run: printenv
        shell: bash
